# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Jami Geter
tagline:             'cyber security, UI, UX, web design, web developer'
url:                 http://blog.jamigeter.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jami 
  url:               https://twitter.com/Jcode_


# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/TheJcode/TheJcode.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:       {'About Me':'/about','Archive':'/archive','Feed':'/atom.xml'}
